/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package supplynote;

import javax.swing.*;

import java.sql.*;
import java.util.UUID;
/**
 *
 * @author aido
 */
public class f_supplier extends javax.swing.JFrame {

    /**
     * Creates new form f_utama
     */
    
    koneksi dbsetting;
    String driver,database, user, pass;
    
    public f_supplier() {
        initComponents();
        
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
        tabel_supplier.setModel(tableModel);
        settableload();
        
//        Hide Column 1
        tabel_supplier.getColumnModel().getColumn(0).setMinWidth(0);
        tabel_supplier.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    private javax.swing.table.DefaultTableModel tableModel=getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {"Kode Supplier","Nama Supplier", "No Telepon", 
                    "Email", "Lokasi", "Negara"}
        ){
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
   
    
    int row = 0;
    private void tampil_field(){
        row = tabel_supplier.getSelectedRow();
        
        txt_supplier.setText(String.valueOf(tableModel.getValueAt(row, 1)));
        txt_noTelp.setText(String.valueOf(tableModel.getValueAt(row, 2)));
        txt_email.setText(String.valueOf(tableModel.getValueAt(row, 3)));
        txt_lokasi.setText(String.valueOf(tableModel.getValueAt(row, 4)));
        txt_negara.setText(String.valueOf(tableModel.getValueAt(row, 5)));
    }
    
    public void membersihkan_teks(){
        txt_supplier.setText("");
        txt_noTelp.setText("");
        txt_email.setText("");
        txt_lokasi.setText("");
        txt_negara.setText("");
    }
    
    String data []=new String[5];
    private void settableload(){
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "SELECT * FROM t_supplier";
            ResultSet res = stt.executeQuery(SQL);
            
            
            tableModel.setRowCount(0);
            while(res.next()){
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
                
            }
            
            res.close();
            stt.close();
            kon.close();
            
            membersihkan_teks();
            
        }catch(Exception ex){
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(), "Error", 
                    JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_barang = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_supplier = new javax.swing.JButton();
        btn_detailTrans = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_supplier = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_noTelp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_lokasi = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        txt_negara = new javax.swing.JTextField();
        txt_supplier = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));

        btn_barang.setText("Barang");
        btn_barang.setBackground(new java.awt.Color(51, 51, 51));
        btn_barang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_barang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_barang.setForeground(new java.awt.Color(255, 255, 255));
        btn_barang.setToolTipText("");
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });

        btn_transaksi.setText("Transaksi");
        btn_transaksi.setBackground(new java.awt.Color(51, 51, 51));
        btn_transaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        btn_supplier.setText("Supplier");
        btn_supplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_supplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_detailTrans.setText("Detail Transaksi");
        btn_detailTrans.setBackground(new java.awt.Color(51, 51, 51));
        btn_detailTrans.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_detailTrans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_detailTrans.setForeground(new java.awt.Color(255, 255, 255));
        btn_detailTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(btn_transaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(btn_detailTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_detailTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(637, Short.MAX_VALUE)))
        );

        jLabel1.setText("Pencatatan Supplier");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel2.setText("Negara");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btn_ubah.setText("Ubah");
        btn_ubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        tabel_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_supplier);

        btn_tambah.setText("Tambah");
        btn_tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Supplier");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel4.setText("No. Telp");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txt_noTelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Email");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Lokasi");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txt_lokasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lokasiActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        txt_negara.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_supplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_supplier)
                                    .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_noTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ubah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(txt_negara, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1478, 806));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:

        // Ambil data dari text field
        String namaSup = txt_supplier.getText();
        String noTelp = txt_noTelp.getText();
        String email = txt_email.getText();
        String lokasi = txt_lokasi.getText();
        String negara = txt_negara.getText();
        
        // Validasi: Pastikan semua field tidak kosong
        if (namaSup.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama supplier belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (noTelp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor telepon belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Nomor telepon harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(null, "Format email tidak valid.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (lokasi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lokasi belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (negara.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Negara belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            
            //generate UUID
            UUID uuid = UUID.randomUUID();
            String kodeSup = uuid.toString();
            
            String sql = "INSERT INTO t_supplier (kode_supplier, nama_supplier, no_telepon,"
                    + "email, lokasi, negara) VALUES (?, ?, ?, ?, ?, ?) ";
            
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, kodeSup);
            pst.setString(2, namaSup);
            pst.setString(3, noTelp);
            pst.setString(4, email);
            pst.setString(5, lokasi);
            pst.setString(6, negara);
            
            int rowInserted = pst.executeUpdate();
            if (rowInserted > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
                settableload();
                membersihkan_teks(); // reset form
            }
  
            pst.close();
            kon.close();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        
        // Ambil Kode Barang dari tabel
        int selectedRow = tabel_supplier.getSelectedRow();
        String kodeSup = tableModel.getValueAt(selectedRow, 1).toString();
        
        // Ambil data dari text field
        String namaSup = txt_supplier.getText();
        String noTelp = txt_noTelp.getText();
        String email = txt_email.getText();
        String lokasi = txt_lokasi.getText();
        String negara = txt_negara.getText();
        
        // Validasi: Pastikan semua field tidak kosong
        if (namaSup.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama supplier belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (noTelp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor telepon belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Nomor telepon harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(null, "Format email tidak valid.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (lokasi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lokasi belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (negara.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Negara belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update ke database
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);

            String sql = "UPDATE t_supplier SET kode_supplier=?, nama_supplier=?, "
                    + "no_telepon=?, email=?, lokasi=?, negara=? WHERE kode_supplier=?";
            PreparedStatement pst = kon.prepareStatement(sql);

            pst.setString(1, kodeSup);
            pst.setString(2, namaSup); 
            pst.setString(3, noTelp);
            pst.setString(4, email);
            pst.setString(5, lokasi);
            pst.setString(6, negara);

            int rowUpdated = pst.executeUpdate();
            if (rowUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah.");
                settableload();
                membersihkan_teks(); // reset form
            }

            pst.close();
            kon.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                    "Gagal mengubah data: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        }           
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void tabel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_supplierMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            tampil_field();
        }
    }//GEN-LAST:event_tabel_supplierMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_supplier.getSelectedRow();
        String kodeSup = tableModel.getValueAt(selectedRow, 1).toString();
        
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);

            String sql = "DELETE FROM t_supplier WHERE kode_supplier= ?";
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, kodeSup);
             
            pst.executeUpdate();
            if(!kodeSup.isEmpty()){
                settableload();
            }
            
            pst.close();
            kon.close();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, 
                    "Gagal mengubah data: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lokasiActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        // TODO add your handling code here:
        f_barang barang = new f_barang();
        barang.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        f_transaksi transaksi = new f_transaksi();
        transaksi.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_detailTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailTransActionPerformed
        // TODO add your handling code here:
        f_detailTransaksi dettransaksi = new f_detailTransaksi();
        dettransaksi.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_detailTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_detailTrans;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_supplier;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_supplier;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lokasi;
    private javax.swing.JTextField txt_negara;
    private javax.swing.JTextField txt_noTelp;
    private javax.swing.JTextField txt_supplier;
    // End of variables declaration//GEN-END:variables
}
